# Generated by Django 4.1.7 on 2023-03-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='bio',
            field=models.TextField(default='bio needed'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='bio',
            field=models.TextField(default='bio needed'),
        ),
    ]
