# Generated by Django 4.1.7 on 2023-03-20 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='team',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.team'),
        ),
    ]
